<script>
  import Saos from "saos";
  import timeline_data from "data/timeline.csv"

  const anim_text = "cubic-bezier(0.250, 0.460, 0.450, 0.940) both"

  const parse_date = (date_text) => {
    let date_array = date_text.split("-")
    return new Date(date_array[2] - 543, date_array[1] - 1, date_array[0])
  }
  const format_date = (date_text) => {
    let date = parse_date(date_text)
    return date.toLocaleDateString("th-TH", { month: "short", day: "numeric" })
  }
  const year_num = (date_text) => {
    let date = parse_date(date_text)
    return +date.getFullYear()
  }

  let current_year
</script>

<style>
  #chats .chat {
    border-radius: 1em;
    display: inline-block;
    max-width: 80%;
    padding: 0.5em 1em;
    margin-top: 1em;
    margin-bottom: 1em;
    box-sizing: border-box;
  }
  #chats .chat-container-right {
    text-align: right;
  }
  #chats .chat.left  {
    border-bottom-left-radius: 2px;
  }
  #chats .chat.right {
    border-bottom-right-radius: 2px;
  }
  #chats .chat.group1  {
    background-color: lightgreen;
  }
  #chats .chat.group2 {
    background-color: skyblue;
  }
  #chats .chat.group3 {
    background-color: lightcoral;
  }

  #chats .year {
    width: 100%;
    text-align: center;
  }
  #chats .date {
    display: inline-block;
  }

  /* ----------------------------------------------
  * Generated by Animista on 2021-6-14 15:38:32
  * Licensed under FreeBSD License.
  * See http://animista.net/license for more info. 
  * w: http://animista.net, t: @cssanimista
  * ---------------------------------------------- */

  /**
  * ----------------------------------------
  * animation scale-in-bl
  * ----------------------------------------
  */
  @-webkit-keyframes -global-scale-in-bl {
    0% {
      -webkit-transform: scale(0);
              transform: scale(0);
      -webkit-transform-origin: 0% 100%;
              transform-origin: 0% 100%;
      opacity: 1;
    }
    100% {
      -webkit-transform: scale(1);
              transform: scale(1);
      -webkit-transform-origin: 0% 100%;
              transform-origin: 0% 100%;
      opacity: 1;
    }
  }
  @keyframes -global-scale-in-bl {
    0% {
      -webkit-transform: scale(0);
              transform: scale(0);
      -webkit-transform-origin: 0% 100%;
              transform-origin: 0% 100%;
      opacity: 1;
    }
    100% {
      -webkit-transform: scale(1);
              transform: scale(1);
      -webkit-transform-origin: 0% 100%;
              transform-origin: 0% 100%;
      opacity: 1;
    }
  }
  @-webkit-keyframes -global-scale-in-br {
    0% {
      -webkit-transform: scale(0);
              transform: scale(0);
      -webkit-transform-origin: 100% 100%;
              transform-origin: 100% 100%;
      opacity: 1;
    }
    100% {
      -webkit-transform: scale(1);
              transform: scale(1);
      -webkit-transform-origin: 100% 100%;
              transform-origin: 100% 100%;
      opacity: 1;
    }
  }
  @keyframes -global-scale-in-br {
    0% {
      -webkit-transform: scale(0);
              transform: scale(0);
      -webkit-transform-origin: 100% 100%;
              transform-origin: 100% 100%;
      opacity: 1;
    }
    100% {
      -webkit-transform: scale(1);
              transform: scale(1);
      -webkit-transform-origin: 100% 100%;
              transform-origin: 100% 100%;
      opacity: 1;
    }
  }
  @-webkit-keyframes -global-fade-in {
    0% {
      opacity: 0;
    }
    100% {
      opacity: 1;
    }
  }
  @keyframes -global-fade-in {
    0% {
      opacity: 0;
    }
    100% {
      opacity: 1;
    }
  }
</style>

<svelte:head>
	<title>ก่อนจะเป็นรัฐธรรมนูญ 2560 - ลำดับเหตุการณ์</title>
</svelte:head>

<h1>จำลองไลน์กลุ่มรัฐธรรมนูญ 2560</h1>

<p>
  รัฐธรรมนูญแห่งราชอาณาจักรไทย พุทธศักราช 2560 ถูกวิพากษ์วิจารณ์อย่างมากในหลายประเด็น ไม่ว่าจะเป็นที่มาของผู้ร่างรัฐธรรมนูญที่ไม่เป็นประชาธิปไตย การสร้างบทบัญญัติที่วางกระบวนการสืบทอดอำนาจให้กับ คสช. คณะรัฐประหารซึ่งยึดอำนาจการปกครองจากรัฐบาลที่มาจากการเลือกตั้ง การปิดกั้นการแสดงความคิดเห็นเกี่ยวกับการทำประชามติร่างรัฐธรรมนูญ รวมถึงการกำหนดประเด็นคำถามในการทำประชามติที่ไม่ชัดเจน ฯลฯ
</p>

<p>
  ก่อนที่รัฐธรรมนูญฉบับนี้จะกำเนิดขึ้นมาได้ ก็มีเหตุการณ์ต่าง ๆ เกิดขึ้นมากมาย ซึ่งมีความเกี่ยวข้องเชื่อมโยงกัน ทั้งจากฝั่งเหตุการณ์ที่สร้างผลสนับสนุน คสช. ในการสร้างรัฐธรรมนูญเพื่อการสืบทอดอำนาจ และฝั่งเหตุการณ์ที่สร้างผลต่อต้าน คสช. ไม่ให้สามารถใช้รัฐธรรมนูญเพื่อสืบทอดอำนาจต่อได้ ซึ่งเหตุการณ์ทั้งสองฝั่งล้วนมีบุคคล กลุ่มบุคคล และองค์กรที่เกี่ยวข้องอย่างหลากหลาย ทั้งจากภาครัฐ ภาคการเมือง และภาคประชาชน
</p>

<p>
  ELECT จะพาทุกคนไปดู Timeline ตั้งแต่เกิดการทำรัฐประหารเมื่อ พ.ศ. 2557 จนถึงการประกาศใช้รัฐธรรมนูญฉบับปัจจุบันเมื่อ พ.ศ. 2560 ผ่านตัวอย่าง “70 เหตุการณ์” เพื่อแสดงให้เห็นว่าก่อนที่จะเกิดเป็นรัฐธรรมนูญ 2560 มีเหตุการณ์อะไรเกิดขึ้นบ้าง รวมถึงผู้ที่มีความเกี่ยวข้องในเรื่องนี้ ทั้งจากฝ่ายสนับสนุนและฝ่ายไม่สนับสนุน คสช. เป็นใคร และทำอะไรที่ส่งผลต่อการเกิดรัฐธรรมนูญ 2560 อันเป็นเครื่องมือสืบทอดอำนาจของ คสช. บ้าง
</p>

<div id="chats">
  <!--
  // ประเภทของเหตุการณ์
  // 1 = เกิดผลสนับสนุน คสช.
  // 2 = เกิดผลต่อต้าน คสช.

  // ผู้กระทำเหตุการณ์
  // 1 = ภาครัฐ (คสช. และองคาพยพ (เจ้าหน้าที่รัฐ หรือผู้ที่มาจากการแต่งตั้งของ คสช.))
  // 2 = ภาคการเมือง (พรรคการเมือง นักการเมือง และกลุ่มการเมือง)
  // 3 = ภาคประชาชน (กลุ่มนักวิชาการ นักศึกษา ประชาชน และ NGO)
  -->

  {#each timeline_data as { event_no, event_name, date, event_type, event_persons, cause }}
    {#if current_year != year_num(date) }
      <Saos animation="fade-in 1.2s {anim_text}" once={true}>
        <div class="year">{ 'พ.ศ. ' + ((current_year = year_num(date)) + 543) }</div>
      </Saos>
    {/if}
    <div class="chat-container-{event_type == 2 ? 'left' : 'right'}">
      <Saos animation="scale-in-b{event_type == 2 ? 'l' : 'r'} 0.5s {anim_text}" once={true}>
        {#if event_type == 1 }
          <div class="date">{format_date(date)}</div>
        {/if}
        <div class="chat group{event_persons} {event_type == 2 ? 'left' : 'right'}">{event_name}</div>
        {#if event_type == 2 }
          <div class="date">{format_date(date)}</div>
        {/if}
      </Saos>
    </div>
  {/each}

</div>