<script>
  import Meta from '../components/Meta.svelte'

  const metadata = {
    title: 'ก่อนจะเป็นรัฐธรรมนูญ 2560',
    description: 'ก่อนจะเป็นรัฐธรรมนูญ 2560',
    image: 'images/og.jpg',
    url:'https://elect.in.th/referendum/'
  }

  import Saos from "saos"

  let w
  const left_or_right = (type) => type == 1 ? 'left' : 'right'

  const anim_text = "cubic-bezier(0.250, 0.460, 0.450, 0.940) both"
  const anim_slide = (type) => `scale-in-b${left_or_right(type).charAt(0)} 0.5s ${anim_text}`
  
  import timeline_data from "data/timeline.csv"

  const parse_date = (date_text) => {
    let date_array = date_text.split("-")
    return new Date(date_array[2] - 543, date_array[1] - 1, date_array[0])
  }
  const format_date = (date_text) => {
    let date = parse_date(date_text)
    return date.toLocaleDateString("th-TH", { month: "short", day: "numeric" })
  }
  const year_num = (date_text) => {
    let date = parse_date(date_text)
    return +date.getFullYear()
  }

  const url_regex = /(http[^\s]+)/g

  let current_year
  for (let i = 0; i < timeline_data.length; i++) {
    let year = year_num(timeline_data[i].date)
    timeline_data[i].show_year = (current_year !== year)
    current_year = year

    let cause = timeline_data[i].cause.split("\n\n")
    timeline_data[i].paragraphs = []
    for (let j = 0; j < cause.length; j++) {
      let urls = [...cause[j].matchAll(url_regex)]
      if (urls.length > 0) {
        timeline_data[i].paragraphs.push(cause[j].split(urls[0][0])[0])
        for (let url of urls) {
          timeline_data[i].paragraphs.push(url[0])
        }
      } else {
        timeline_data[i].paragraphs.push(cause[j])
      }
    }
  }
</script>

<style>
  .legend {
    display: flex;
    flex-direction: row;
    flex-wrap: nowrap;
    align-items: center;
  }
  .legend.alignment {
    justify-content: space-between;
    color: dimgray;
  }
  .legend.color {
    justify-content: space-evenly;
    margin-top: 1em;
    margin-bottom: 2em;
  }
  .legend .ball {
    margin-right: 0.4em;
    padding: 0;
    border-radius: 0.75em;
    width: 1.5em;
    height: 1.5em;
  }

  .chat-container-left {
    margin-top: 1em;
    margin-bottom: 1em;
  }
  .chat-container-right {
    margin-top: 1em;
    margin-bottom: 1em;
    text-align: right;
  }

  .chat {
    border-radius: 1em;
    display: inline-block;
    max-width: 75%;
    padding: 0.5em 1em;
    margin-top: 0.2em;
    margin-bottom: 0.2em;
    box-sizing: border-box;
  }
  .chat.left  {
    border-top-left-radius: 2px;
  }
  .chat.right {
    border-top-right-radius: 2px;
  }

  .chat.group0 {
    background-color: var(--color0);
  }
  .chat.group1 {
    background-color: var(--color1);
  }
  .chat.group2 {
    background-color: var(--color2);
  }
  .chat.group3 {
    background-color: var(--color3);
  }

  .chat.cause {
    background-color: transparent;
    border-width: 1.5px;
    border-style: solid;
  }
  .chat.cause.group0 {
    border-color: var(--color0);
  }
  .chat.cause.group1 {
    border-color: var(--color1);
  }
  .chat.cause.group2 {
    border-color: var(--color2);
  }
  .chat.cause.group3 {
    border-color: var(--color3);
  }

  .actor {
    font-weight: bold;
    filter: brightness(85%);
    display: inline-block;
  }
  .actor.group0 {
    color: var(--color0);
  }
  .actor.group1 {
    color: var(--color1);
  }
  .actor.group2 {
    color: var(--color2);
  }
  .actor.group3 {
    color: var(--color3);
  }

  img.chat {
    padding: 0;
    max-width: 250px;
  }
  /* img.chat.group1  {
    border-color: var(--color1);
  }
  img.chat.group2 {
    border-color: var(--color2);
  }
  img.chat.group3 {
    border-color: var(--color3);
  } */

  .year-container {
    width: 100%;
    text-align: center;
    margin: 0 auto;
  }
  .year {
    background-color: gainsboro;
    color: dimgray;
    border-radius: 1em;
    display: inline-block;
    padding: 0.5em 1em;
  }
  .year.hidden {
    display: none;
  }
  .date {
    display: inline-block;
    color: darkgray;
  }
  .date.left {
    margin-left: 0.5em;
  }
  .date.right {
    margin-right: 0.5em;
  }

  .link img {
    display: inline-block;
    vertical-align: top;
    width: 41px;
    padding: 0.5em 0;
  }
  .link div {
    display: inline-block;
    vertical-align: top;
    width: calc(100% - 41px - 1em);
    margin-left: 0.5em;
  }
  .link p.icon-click-text {
    margin-bottom: 0;
    opacity: 0.5;
    font-size: 0.8em;
  }

  /* ----------------------------------------------
  * Generated by Animista on 2021-6-14 15:38:32
  * Licensed under FreeBSD License.
  * See http://animista.net/license for more info. 
  * w: http://animista.net, t: @cssanimista
  * ---------------------------------------------- */

  /**
  * ----------------------------------------
  * animation scale-in-bl
  * ----------------------------------------
  */
  @-webkit-keyframes -global-scale-in-bl {
    0% {
      -webkit-transform: scale(0);
              transform: scale(0);
      -webkit-transform-origin: 0% 100%;
              transform-origin: 0% 100%;
      opacity: 1;
    }
    100% {
      -webkit-transform: scale(1);
              transform: scale(1);
      -webkit-transform-origin: 0% 100%;
              transform-origin: 0% 100%;
      opacity: 1;
    }
  }
  @keyframes -global-scale-in-bl {
    0% {
      -webkit-transform: scale(0);
              transform: scale(0);
      -webkit-transform-origin: 0% 100%;
              transform-origin: 0% 100%;
      opacity: 1;
    }
    100% {
      -webkit-transform: scale(1);
              transform: scale(1);
      -webkit-transform-origin: 0% 100%;
              transform-origin: 0% 100%;
      opacity: 1;
    }
  }
  @-webkit-keyframes -global-scale-in-br {
    0% {
      -webkit-transform: scale(0);
              transform: scale(0);
      -webkit-transform-origin: 100% 100%;
              transform-origin: 100% 100%;
      opacity: 1;
    }
    100% {
      -webkit-transform: scale(1);
              transform: scale(1);
      -webkit-transform-origin: 100% 100%;
              transform-origin: 100% 100%;
      opacity: 1;
    }
  }
  @keyframes -global-scale-in-br {
    0% {
      -webkit-transform: scale(0);
              transform: scale(0);
      -webkit-transform-origin: 100% 100%;
              transform-origin: 100% 100%;
      opacity: 1;
    }
    100% {
      -webkit-transform: scale(1);
              transform: scale(1);
      -webkit-transform-origin: 100% 100%;
              transform-origin: 100% 100%;
      opacity: 1;
    }
  }
  @-webkit-keyframes -global-fade-in {
    0% {
      opacity: 0;
    }
    100% {
      opacity: 1;
    }
  }
  @keyframes -global-fade-in {
    0% {
      opacity: 0;
    }
    100% {
      opacity: 1;
    }
  }
</style>

<svelte:head>
  <title>ก่อนจะเป็นรัฐธรรมนูญ 2560 - ลำดับเหตุการณ์</title>
  <Meta {metadata}/>
</svelte:head>

<h1>จำลองไลน์กลุ่มรัฐธรรมนูญ 2560</h1>

<p class="first" bind:clientWidth={w}>
  มีเหตุการณ์มากมายที่เกี่ยวข้องกับการเกิดขึ้นของรัฐธรรมนูญ 2560 ซึ่งได้ชื่อว่าเป็นรัฐธรรมนูญซึ่งวางเส้นทางการสืบทอดอำนาจให้กับ คสช. อย่างเป็นระบบ ทั้งจากฝั่งสนับสนุนให้เกิดรัฐธรรมนูญ 2560 และฝั่งที่ต่อต้านไม่ให้เกิดรัฐธรรมนูญ 2560 โดยแต่ละฝั่งก็มีบุคคล กลุ่มบุคคล และองค์กรที่เข้ามาเกี่ยวข้องจำนวนมาก ทั้งที่มาจากภาครัฐ ภาคการเมือง และภาคประชาชน
</p>

<p>
  ร่วมกันทำความรู้จักเหตุการณ์และผู้ที่เกี่ยวข้องกับรัฐธรรมนูญ 2560 ได้ที่นี่
</p>

<div id="chats">
  <!--
  // ประเภทของเหตุการณ์
  // 1 = เกิดผลสนับสนุน คสช.
  // 2 = เกิดผลต่อต้าน คสช.

  // ผู้กระทำเหตุการณ์
  // 1 = ภาครัฐ (คสช. และองคาพยพ (เจ้าหน้าที่รัฐ หรือผู้ที่มาจากการแต่งตั้งของ คสช.))
  // 2 = ภาคการเมือง (พรรคการเมือง นักการเมือง และกลุ่มการเมือง)
  // 3 = ภาคประชาชน (กลุ่มนักวิชาการ นักศึกษา ประชาชน และ NGO)
  -->
  
  <div class="legend alignment">
    <div class="chat group0 {left_or_right(1)}">เกิดผลสนับสนุน คสช.</div>
    <div class="chat group0 {left_or_right(2)}">เกิดผลต่อต้าน คสช.</div>
  </div>
  <div class="legend color">
    <div class="legend">
      <div class="chat group1 ball"></div>
      <div class="actor group1">ภาครัฐ</div>
    </div>
    <div class="legend">
      <div class="chat group2 ball"></div>
      <div class="actor group2">ภาคการเมือง</div>
    </div>
    <div class="legend">
      <div class="chat group3 ball"></div>
      <div class="actor group3">ภาคประชาชน</div>
    </div>
  </div>

  {#each timeline_data as { event_no, event_actor, event_name, date, event_type, event_persons, cause, icon_txt, icon_link, show_year, paragraphs }}
    <Saos animation="fade-in 1.2s {anim_text}" once={true}>
      <div class="year-container">
        <div class="year {show_year ? '' : 'hidden'}">{'พ.ศ. ' + (year_num(date) + 543)}</div>
      </div>
    </Saos>
    <div class="chat-container-{left_or_right(event_type)}">
      <Saos animation={anim_slide(event_type)} once={true}>
        <div class="actor group{event_persons} {left_or_right(event_type)}">{event_actor}</div>
      </Saos>
      {#if icon_txt == undefined }
        <Saos animation={anim_slide(event_type)} once={true}>
          <img class="chat group{event_persons} {left_or_right(event_type)}" src="images/event_{`${event_no}`.padStart(2, "0")}.jpg" alt="event" />
        </Saos>
      {/if}
      <Saos animation={anim_slide(event_type)} once={true}>
        {#if event_type == 2 }
          <div class="date right">{format_date(date)}</div>
        {/if}
        <div class="chat group{event_persons} {left_or_right(event_type)}">{event_name}</div>
        {#if event_type == 1 }
          <div class="date left">{format_date(date)}</div>
        {/if}
      </Saos>
      {#each paragraphs as paragraph}
        <Saos animation={anim_slide(event_type)} once={true}>
          <div class="chat cause group{event_persons} {left_or_right(event_type)}">
            {#if paragraph.match(url_regex) }
              <a href={paragraph}>{paragraph.length > w/13 ? (paragraph.substring(0, w/13) + '…') : paragraph}</a>
            {:else}
              {paragraph}
            {/if}
          </div>
        </Saos>
      {/each}
      {#if icon_txt }
        <Saos animation={anim_slide(event_type)} once={true}>
          <a href={icon_link}>
            <div class="chat cause group{event_persons} {left_or_right(event_type)} link">
              <img src="images/pdf.jpg" alt="icon" />
              <div>
                {icon_txt}
                <p class="icon-click-text">คลิกเพื่ออ่านเพิ่มเติม</p>
              </div>
            </div>
          </a>
        </Saos>
      {/if}
    </div>
  {/each}

</div>