<script>
  import Meta from '../components/Meta.svelte'

  const metadata = {
    title: 'ก่อนจะเป็นรัฐธรรมนูญ 2560',
    description: 'ก่อนจะเป็นรัฐธรรมนูญ 2560',
    image: 'images/pie.jpg',
    url:'https://elect.in.th/referendum/'
  }

  import Saos from "saos"

  let w
  const anim_text = "cubic-bezier(0.250, 0.460, 0.450, 0.940) both"
  
  import timeline_data from "data/timeline.csv"

  const parse_date = (date_text) => {
    let date_array = date_text.split("-")
    return new Date(date_array[2] - 543, date_array[1] - 1, date_array[0])
  }
  const format_date = (date_text) => {
    let date = parse_date(date_text)
    return date.toLocaleDateString("th-TH", { month: "short", day: "numeric" })
  }
  const year_num = (date_text) => {
    let date = parse_date(date_text)
    return +date.getFullYear()
  }

  const url_regex = /(http[^\s]+)/g

  let current_year
  for (let i = 0; i < timeline_data.length; i++) {
    let year = year_num(timeline_data[i].date)
    timeline_data[i].show_year = (current_year !== year)
    current_year = year

    let cause = timeline_data[i].cause.split("\n\n")
    timeline_data[i].paragraphs = []
    for (let j = 0; j < cause.length; j++) {
      let urls = [...cause[j].matchAll(url_regex)]
      if (urls.length > 0) {
        timeline_data[i].paragraphs.push(cause[j].split(urls[0][0])[0])
        for (let url of urls) {
          timeline_data[i].paragraphs.push(url[0])
        }
      } else {
        timeline_data[i].paragraphs.push(cause[j])
      }
    }
  }
</script>

<style>
  #chats .chat-container-left {
    margin-top: 1em;
    margin-bottom: 1em;
  }
  #chats .chat-container-right {
    margin-top: 1em;
    margin-bottom: 1em;
    text-align: right;
  }

  #chats .chat {
    border-radius: 1em;
    display: inline-block;
    max-width: 75%;
    padding: 0.5em 1em;
    margin-top: 0.2em;
    margin-bottom: 0.2em;
    box-sizing: border-box;
  }
  #chats .chat.left  {
    border-top-left-radius: 2px;
  }
  #chats .chat.right {
    border-top-right-radius: 2px;
  }

  #chats .chat.group1  {
    background-color: var(--color1);
  }
  #chats .chat.group2 {
    background-color: var(--color2);
  }
  #chats .chat.group3 {
    background-color: var(--color3);
  }

  #chats .chat.cause {
    background-color: transparent;
    border-width: 1.5px;
    border-style: solid;
  }
  #chats .chat.cause.group1  {
    border-color: var(--color1);
  }
  #chats .chat.cause.group2 {
    border-color: var(--color2);
  }
  #chats .chat.cause.group3 {
    border-color: var(--color3);
  }

  #chats .actor {
    font-weight: bold;
    filter: brightness(80%);
  }
  #chats .actor.group1  {
    color: var(--color1);
  }
  #chats .actor.group2 {
    color: var(--color2);
  }
  #chats .actor.group3 {
    color: var(--color3);
  }

  #chats img.chat {
    padding: 1.5px;
  }
  #chats img.chat.group1  {
    border-color: var(--color1);
  }
  #chats img.chat.group2 {
    border-color: var(--color2);
  }
  #chats img.chat.group3 {
    border-color: var(--color3);
  }

  #chats .year {
    width: 100%;
    text-align: center;
    font-family: Kondolar Thai, serif;
  }
  #chats .year.hidden {
    display: none;
  }
  #chats .date {
    display: inline-block;
  }
  #chats .date.left {
    margin-left: 0.5em;
  }
  #chats .date.right {
    margin-right: 0.5em;
  }

  /* ----------------------------------------------
  * Generated by Animista on 2021-6-14 15:38:32
  * Licensed under FreeBSD License.
  * See http://animista.net/license for more info. 
  * w: http://animista.net, t: @cssanimista
  * ---------------------------------------------- */

  /**
  * ----------------------------------------
  * animation scale-in-bl
  * ----------------------------------------
  */
  @-webkit-keyframes -global-scale-in-bl {
    0% {
      -webkit-transform: scale(0);
              transform: scale(0);
      -webkit-transform-origin: 0% 100%;
              transform-origin: 0% 100%;
      opacity: 1;
    }
    100% {
      -webkit-transform: scale(1);
              transform: scale(1);
      -webkit-transform-origin: 0% 100%;
              transform-origin: 0% 100%;
      opacity: 1;
    }
  }
  @keyframes -global-scale-in-bl {
    0% {
      -webkit-transform: scale(0);
              transform: scale(0);
      -webkit-transform-origin: 0% 100%;
              transform-origin: 0% 100%;
      opacity: 1;
    }
    100% {
      -webkit-transform: scale(1);
              transform: scale(1);
      -webkit-transform-origin: 0% 100%;
              transform-origin: 0% 100%;
      opacity: 1;
    }
  }
  @-webkit-keyframes -global-scale-in-br {
    0% {
      -webkit-transform: scale(0);
              transform: scale(0);
      -webkit-transform-origin: 100% 100%;
              transform-origin: 100% 100%;
      opacity: 1;
    }
    100% {
      -webkit-transform: scale(1);
              transform: scale(1);
      -webkit-transform-origin: 100% 100%;
              transform-origin: 100% 100%;
      opacity: 1;
    }
  }
  @keyframes -global-scale-in-br {
    0% {
      -webkit-transform: scale(0);
              transform: scale(0);
      -webkit-transform-origin: 100% 100%;
              transform-origin: 100% 100%;
      opacity: 1;
    }
    100% {
      -webkit-transform: scale(1);
              transform: scale(1);
      -webkit-transform-origin: 100% 100%;
              transform-origin: 100% 100%;
      opacity: 1;
    }
  }
  @-webkit-keyframes -global-fade-in {
    0% {
      opacity: 0;
    }
    100% {
      opacity: 1;
    }
  }
  @keyframes -global-fade-in {
    0% {
      opacity: 0;
    }
    100% {
      opacity: 1;
    }
  }
</style>

<svelte:head>
  <title>ก่อนจะเป็นรัฐธรรมนูญ 2560 - ลำดับเหตุการณ์</title>
  <Meta {metadata}/>
</svelte:head>

<h1>จำลองไลน์กลุ่มรัฐธรรมนูญ 2560</h1>

<p bind:clientWidth={w}>
  รัฐธรรมนูญแห่งราชอาณาจักรไทย พุทธศักราช 2560 ถูกวิพากษ์วิจารณ์อย่างมากในหลายประเด็น ไม่ว่าจะเป็นที่มาของผู้ร่างรัฐธรรมนูญที่ไม่เป็นประชาธิปไตย การสร้างบทบัญญัติที่วางกระบวนการสืบทอดอำนาจให้กับ คสช. คณะรัฐประหารซึ่งยึดอำนาจการปกครองจากรัฐบาลที่มาจากการเลือกตั้ง การปิดกั้นการแสดงความคิดเห็นเกี่ยวกับการทำประชามติร่างรัฐธรรมนูญ รวมถึงการกำหนดประเด็นคำถามในการทำประชามติที่ไม่ชัดเจน ฯลฯ
</p>

<p>
  ก่อนที่รัฐธรรมนูญฉบับนี้จะกำเนิดขึ้นมาได้ ก็มีเหตุการณ์ต่าง ๆ เกิดขึ้นมากมาย ซึ่งมีความเกี่ยวข้องเชื่อมโยงกัน ทั้งจากฝั่งเหตุการณ์ที่สร้างผลสนับสนุน คสช. ในการสร้างรัฐธรรมนูญเพื่อการสืบทอดอำนาจ และฝั่งเหตุการณ์ที่สร้างผลต่อต้าน คสช. ไม่ให้สามารถใช้รัฐธรรมนูญเพื่อสืบทอดอำนาจต่อได้ ซึ่งเหตุการณ์ทั้งสองฝั่งล้วนมีบุคคล กลุ่มบุคคล และองค์กรที่เกี่ยวข้องอย่างหลากหลาย ทั้งจากภาครัฐ ภาคการเมือง และภาคประชาชน
</p>

<p>
  ELECT จะพาทุกคนไปดู Timeline ตั้งแต่เกิดการทำรัฐประหารเมื่อ พ.ศ. 2557 จนถึงการประกาศใช้รัฐธรรมนูญฉบับปัจจุบันเมื่อ พ.ศ. 2560 ผ่านตัวอย่าง “70 เหตุการณ์” เพื่อแสดงให้เห็นว่าก่อนที่จะเกิดเป็นรัฐธรรมนูญ 2560 มีเหตุการณ์อะไรเกิดขึ้นบ้าง รวมถึงผู้ที่มีความเกี่ยวข้องในเรื่องนี้ ทั้งจากฝ่ายสนับสนุนและฝ่ายไม่สนับสนุน คสช. เป็นใคร และทำอะไรที่ส่งผลต่อการเกิดรัฐธรรมนูญ 2560 อันเป็นเครื่องมือสืบทอดอำนาจของ คสช. บ้าง
</p>

<div id="chats">
  <!--
  // ประเภทของเหตุการณ์
  // 1 = เกิดผลสนับสนุน คสช.
  // 2 = เกิดผลต่อต้าน คสช.

  // ผู้กระทำเหตุการณ์
  // 1 = ภาครัฐ (คสช. และองคาพยพ (เจ้าหน้าที่รัฐ หรือผู้ที่มาจากการแต่งตั้งของ คสช.))
  // 2 = ภาคการเมือง (พรรคการเมือง นักการเมือง และกลุ่มการเมือง)
  // 3 = ภาคประชาชน (กลุ่มนักวิชาการ นักศึกษา ประชาชน และ NGO)
  -->

  {#each timeline_data as { event_no, event_actor, event_name, date, event_type, event_persons, cause, show_year, paragraphs }}
    <Saos animation="fade-in 1.2s {anim_text}" once={true}>
      <div class="year {show_year ? '' : 'hidden'}">{'พ.ศ. ' + (year_num(date) + 543)}</div>
    </Saos>
    <div class="chat-container-{event_type == 1 ? 'left' : 'right'}">
      <Saos animation="scale-in-b{event_type == 1 ? 'l' : 'r'} 0.5s {anim_text}" once={true}>
        <div class="actor group{event_persons} {event_type == 1 ? 'left' : 'right'}">{event_actor}</div>
      </Saos>
      <Saos animation="scale-in-b{event_type == 1 ? 'l' : 'r'} 0.5s {anim_text}" once={true}>
        {#if event_type == 2 }
          <div class="date right">{format_date(date)}</div>
        {/if}
        <div class="chat group{event_persons} {event_type == 1 ? 'left' : 'right'}">{event_name}</div>
        {#if event_type == 1 }
          <div class="date left">{format_date(date)}</div>
        {/if}
      </Saos>
      <Saos animation="scale-in-b{event_type == 1 ? 'l' : 'r'} 0.5s {anim_text}" once={true}>
        <img class="chat group{event_persons} {event_type == 1 ? 'left' : 'right'}" src="images/event_{`${event_no}`.padStart(2, "0")}.jpg" alt="event" />
      </Saos>
      {#each paragraphs as paragraph}
        <Saos animation="scale-in-b{event_type == 1 ? 'l' : 'r'} 0.5s {anim_text}" once={true}>
          <div class="chat cause group{event_persons} {event_type == 1 ? 'left' : 'right'}">
            {#if paragraph.match(url_regex) }
              <a href={paragraph}>{paragraph.length > w/12 ? (paragraph.substring(0, w/12) + '…') : paragraph}</a>
            {:else}
              {paragraph}
            {/if}
          </div>
        </Saos>
      {/each}
    </div>
  {/each}

</div>